# Generated by Django 5.2.3 on 2025-06-19 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='vet_sprint.mascota')),
            ],
            options={
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
