# Generated by Django 5.2.3 on 2025-06-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_sprint', '0002_alter_mascota_options_alter_propietario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='vet_sprint.mascota')),
            ],
            options={
                'verbose_name_plural': 'Cirugías',
                'ordering': ['fecha'],
            },
        ),
    ]
