# Generated by Django 5.2.3 on 2025-06-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_sprint', '0003_medicamento_cirugia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='vet_sprint.mascota')),
            ],
            options={
                'verbose_name_plural': 'Bitácoras de Consulta',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
